scss_files: '*.scss'

linters:

  SelectorFormat:
    enabled: false
    convention: camel_case 

  ImportantRule:
    enabled: false

  NestingDepth:
    enabled: true
    max_depth: 4
    ignore_parent_selectors: false

  SelectorDepth:
    enabled: true
    max_depth: 4

  VendorPrefix: 
    enabled: false
